### ISSUE TITLE
То работает, то не работает

### ISSUE THREAD

**Issue by avbolsh** [alei1180/ocvc#5]
Запускаю. Иногда срабатывает. Иногда нет. Хорошо бы логи какие-то видеть (т.е. может скрипт там ругается на что-то)
![jMUJB2PHez](https://github.com/user-attachments/assets/dc9230ae-4392-4493-bdd0-9f8c5fcd022b)

**Comment by alei1180** [comment]
@avbolsh не увидел на вашем примере:
1) скопировать выделенный участок кода в буфер обмена `CTRL + C`
2) не закрывая конфигуратор нажать `ALT + SHIFT + V`

**Comment by avbolsh** [comment]
Экранная клавиатура windows показывает только нажатие контролов, шифтов итд. не хотелось искать какую-то специальную программу. Да, я нажимаю ctrl + c, потом alt + shift + v. 
использую последнюю. 
сначала не хотела работать. потом запускал под админом. работала. потом работа  и не под админом ( я локальный админ, сам компьютер в домене, возможно тут какие-то проблемы могут быть)

**Comment by alei1180** [comment]
> сначала не хотела работать. потом запускал под админом. работала. потом работа и не под админом ( я локальный админ, сам компьютер в домене, возможно тут какие-то проблемы могут быть)

@avbolsh спасибо за обратную связь, начну с лога.

**Comment by alei1180** [comment]
> он ругался на то что мол не может найти файл (а файл-обработки лежит в сетевом каталоге. и как будто он в название файла(bsl) пытался впихнуть путь)
> хотя я убил скрипт, а потом опять запустил. он сработал.
> и сейчас опять все заработало. и уже работает опять из утилиты ¯_(ツ)_/¯

@avbolsh cпасибо вам за потраченное время, для уточнения деталей. Попробую воспроизвести вашу ситуацию чтобы отладить и решить проблему.

**Comment by alei1180** [comment]
@avbolsh нашел причину - [исправил](https://github.com/alei1180/ocvc/commit/33ed5165713f47a5ed800ed608faf8fc76b9480e). Изменение войдёт в ближайшее время в релиз `1.3`.
Благодарю за участие в обнаружении и решении проблемы!
